### ISSUE TITLE
Build either locally or in the docker container

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk-cli#3]
After the code here keeps updated with the latest Go CLI, we should make sure the Go CLI can be built into binaries either locally or by docker container.

**Comment by dubeejw** [comment]
In addition we plan on adding the generated binaries to a download section in the git repo.

**Comment by houshengbo** [comment]
@dubeejw How soon do we generate the binaries? Do you mean we can do the build like every major release by adding tag as we did for openwhisk-wskdeploy? The binaries can be accessed via https://github.com/openwhisk/openwhisk-wskdeploy/releases.

**Comment by dubeejw** [comment]
@houshengbo, yes we want to host the binaries under the releases section in Github.

**Comment by houshengbo** [comment]
@dubeejw cool. We definitely can add that. Currently, the README has been updated as we are able to build either with go command directly or with the docker container.

I think we can add the travis support to build the versions for mac, linux and windows.

**Comment by houshengbo** [comment]
https://github.com/openwhisk/openwhisk-cli/releases 
@dubeejw @mdeuser @csantanapr @pritidesai @rabbah @lzbj 
Folks, we are now able to build the openwhisk cli automatically, each time we tag a commit in master. Y!!!!!!!!!!!!!!!!

**Comment by csantanapr** [comment]
YES !!!
💯 👍 🥇 🙌 🚀 🎉 
🌮 🌮 🌮 🌮 🌮 🌮

**Comment by dubeejw** [comment]
Hmm, I have a comment on this PR that was merged: https://github.com/openwhisk/openwhisk-cli/pull/4/files. Where are the externalized strings being bundled into the CLI binaries?

**Comment by dubeejw** [comment]
@houshengbo, @pritidesai, see my above comment.

**Comment by pritidesai** [comment]
@dubeejw I have the PR here for externalized string: https://github.com/openwhisk/openwhisk-cli/pull/13

**Comment by houshengbo** [comment]
The binaries are able to publish on the releases page by travis.
